### ISSUE TITLE
functional walkthrough to identify issues

### ISSUE THREAD

**Issue by momokokong** [justkuper/Nestify#92]

**Comment by justkuper** [comment]
1. SIGN UP PAGE SHOULD FIT SCREEN BECAUSE THE SCROLL BAR MOVES THE LOGO AND MAKES IT OFF CENTER FROM HOMEPAGE AND LOGIN
2. HOMEPAGE - CHANGE "HOME TAKER" TO CLEANER, PROFESSIONAL, OR MAID
3. HOMEPAGE - CHANGE "LAST REVIEW" TO "LATEST REVIEW"
4. HOMEPAGE - USER 1 HAS A 5 STAR REVIEW, WHILE USERS 2&3 HAVE A 4 STAR REVIEW. FIX USERS 2&3
5. SIGN UP - CHANGE "TELL US ABOUT YOU" TO "TELL US ABOUT YOURSELF"
